server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: root
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      nico: false
      http: true
      local: false
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  lavasrc:
    sources:
      spotify: false
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: false
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: true
      jiosaavn: false
    ytdlp:
      path: "/usr/local/bin/yt-dlp"
      searchLimit: 10
      mixPlaylistLoadLimit: 25
      playlistLoadLimit: 100

logging:
  level:
    root: INFO
    lavalink: INFO
